version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      opentelemetry:
        patterns:
          - "@opentelemetry/*"
      aws:
        patterns:
          - "@aws-lambda-powertools/*"
          - "@types/aws-lambda"
      runtime:
        patterns:
          - "zod"
      development:
        patterns:
          - "@types/*"
          - "!@types/aws-lambda"
          - "@biomejs/*"
          - "vitest"
          - "@vitest/*"
          - "typescript"
          - "tsup"
