version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      opentelemetry:
        patterns:
          - "@opentelemetry/*"
      development:
        patterns:
          - "@types/*"
          - "@biomejs/*"
          - "vitest"
          - "@vitest/*"
          - "typescript"
          - "tsup"
