export type { ReadableSpan } from '@opentelemetry/sdk-trace-base'
export {
  assertNoSpan,
  assertSpanExists,
  findSpan,
  findSpans,
  getSpanAttribute,
  getSpanAttributes,
  hasSpan,
  type SpanMatcher,
  spanHasAttribute,
} from './assertions'
export { InMemorySpanExporter } from './exporter'
export {
  createMockAlbEvent,
  createMockApiGatewayEvent,
  createMockApiGatewayV2Event,
  createMockCloudWatchLogsEvent,
  createMockContext,
  createMockDynamoDbEvent,
  createMockDynamoDbRecord,
  createMockEventBridgeEvent,
  createMockKafkaEvent,
  createMockKinesisEvent,
  createMockKinesisRecord,
  createMockS3Event,
  createMockS3Record,
  createMockSnsEvent,
  createMockSnsRecord,
  createMockSqsEvent,
  createMockSqsRecord,
  type MockAlbEventOptions,
  type MockApiGatewayEventOptions,
  type MockApiGatewayV2EventOptions,
  type MockCloudWatchLogsEventOptions,
  type MockContextOptions,
  type MockDynamoDbEventOptions,
  type MockDynamoDbRecordOptions,
  type MockEventBridgeEventOptions,
  type MockKafkaEventOptions,
  type MockKafkaRecordOptions,
  type MockKinesisEventOptions,
  type MockKinesisRecordOptions,
  type MockS3EventOptions,
  type MockS3RecordOptions,
  type MockSnsEventOptions,
  type MockSnsMessageOptions,
  type MockSqsEventOptions,
  type MockSqsRecordOptions,
} from './mocks/index'
export { createTestSdk, type TestSdk, type TestSdkOptions } from './sdk'
